---
title: "Weekly Schedule and Assignments"
---

## Week 1

[Week 1: Course Intro (Slides)](https://sarahshy.github.io/PSU-STAT-184/current/ClassNotes/week-01/course_intro.html)

[Week 1: Course Intro (Doc)](https://sarahshy.github.io/PSU-STAT-184/current/ClassNotes/week-01/course_intro.nb.html)  

Assignments (Due Tuesday, January 21 11:59pm):  

- Canvas reading quiz (DC Chapter 1 & 2)
- Week 1: DataCamp Assignment
- Week 1: GitHub Assignment 

## Week 2
[Week 2: Slides (Tidy Data)](https://sarahshy.github.io/PSU-STAT-184/current/ClassNotes/week-02/tidyData-computing.html)

Assignments (Due Tuesday, January 28 11:59pm):

- Canvas reading quiz (DC Chapter 3 & 4)
- Lab activity: Tidy data
- Homework: DC eBook Ch. 1 & 2 Exercises

## Week 3
[Week 3: Command Patterns, GitHub, RMarkdown (Slides)](https://mdbeckman.github.io/PSU-STAT-184/2019%20Fall/ClassNotes/week-03/week3-notes.html)

[Week 3: Command Patterns, GitHub, RMarkdown (Doc)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-03/week3-notes.nb.html)

Assignments (Due Tuesday, February 4 11:59pm):

- Canvas reading quiz (DC Chapters 5 & 6)
- Lab activity: Markdown Class Schedule
- Homework: DC eBook Ch. 3 & 4 Exercises (Submit PDF on Canvas)


## Week 4
[Week 4: Visualization Concepts (Slides)](https://mdbeckman.github.io/PSU-STAT-184/2019%20Fall/ClassNotes/week-04/VisualizationConcepts.html)

[Week 4: Visualization Concepts (Doc)](https://mdbeckman.github.io/PSU-STAT-184/2019%20Fall/ClassNotes/week-04/VisualizationConcepts.nb.html)


Assignments (Due Tuesday, February 11 11:59pm):

- Canvas reading quiz (DC Chapter 7)
- Lab activity: Graphical Exploration
- Homework: DC eBook Ch. 5 & 6 Exercises (Submit R Notebook on Canvas, Rmd and Notebook on GitHub)


## Week 5
[Week 5: Wrangling and Data Verbs (Slides)](https://mdbeckman.github.io/PSU-STAT-184/2019%20Fall/ClassNotes/week-05/WranglingDataVerbIntro.html)

[Week 5: Wrangling and Data Verbs (Doc)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-05/WranglingDataVerbIntro.nb.html)


Assignments (Due Tuesday, February 18 11:59pm):

- Canvas reading quiz (DC Chapter 9)
- Lab activity: HELPrct
- Homework: DC eBook Ch. 7 Exercises (Submit R Notebook on Canvas, Rmd and Notebook on GitHub)

## Week 6
[Week 6: More Wrangling and Data Verbs (Slides)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-06/WranglingDataVerb2.html)

[Week 6: More Wrangling and Data Verbs (Doc)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-06/WranglingDataVerb2.nb.html)

Assignments (Due Tuesday, February 25 11:59pm):

- Canvas reading quiz (DC Chapter 10)
- Lab activity: Popular Names
- Homework: DC eBook Ch. 10 Exercises (Submit R Notebook on Canvas, Rmd and Notebook on GitHub)

## Week 7
[Week 7: Table Joins (Slides)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-07/Joins.html)

[Week 7: Table Joins (Doc)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-07/Joins.nb.html)

Assignments (Due Tuesday, March 3 11:59pm):

- Canvas reading quiz (DC Chapter 8: Graphics & their grammar)
- Lab activity: Bird Species
- Homework: DC eBook Ch. 10 Exercises (Submit R Notebook on Canvas, Rmd and Notebook on GitHub)

## Week 8
[Week 8: ggplot2 (Slides)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-08/ggplotSlides.html)

[Week 8: ggplot2 (Doc)](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-08/ggplotSlides.nb.html)

Assignments (Due Tuesday, March 17 11:59pm):

- Canvas reading quiz (DC Chapter 12: Wide vs. Narrow)
- Lab activity: Bicycle Sharing
- Homework: DC eBook Ch. 8 Exercises (Submit R Notebook on Canvas, Rmd and Notebook on GitHub)
- Final project: Submit two topic ideas

## Week 9
[Week 9: Wide vs Narrow Data Layouts](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-09/wideNarrowSlides.nb.html)

Assignments (Due Tuesday, March 24 11:59pm):

- Canvas reading quiz (DC Chapter 13+16: Ranks + Data Intake)
- Lab activity: No lab (Midterm week)
- Homework: DC Exercises (ch 12 - wide vs narrow data)

## Week 10

[Week 10: Ranks and Data Intake](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-10/ranks_intake_notes.nb.html)

Assignments (Due Tuesday, March 31 11:59pm):

- Canvas reading quiz (DC Chapter 15 - Statistics concepts)
- Lab activity: Scraping Nuclear Reactors
- Homework: DC Exercises (ch 13 & 16) (Submit R Notebook on Canvas, Rmd and Notebook on GitHub)


## Week 11

[Week 11: Statistical Foundations](https://mdbeckman.github.io/PSU-STAT-184/current/ClassNotes/week-11/StatFoundationsSlides.nb.html)

Assignments (Due Tuesday, April 7 11:59pm):

- Canvas reading quiz (DC Chapter 17 - Regular expressions)
- Lab activity: Statistics of Gene Expression
- Homework: DC Exercises (ch 15 -- Statistics) (Submit R Notebook on Canvas, Rmd and Notebook on GitHub)
- Final Project: Preliminary EDA

## Week 12
